version: '3.1'

services:
  db:
    image: 'postgres:latest'
    container_name: db-measureService
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: measureService
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db-measureService:/var/lib/postgresql/data

volumes:
  db-measureService:
